Add tracer table to data/initialise.sql and data/initialise_local.sql
PolicyEngine/policyengine-api pull request #1758
Opened 2024-09-03 01:17 UTC by leehengpan

Added tracer table to `data/initialise.sql`  and `data/initialise_local.sql`.

2024-09-04 15:51 UTC, anth-volk reviewed
I've made a couple comments/suggestions, but so far, I think this is good progress! Thanks @leehengpan for your work on this. Feel free to re-request review whenever necessary, but might make sense to re-review when there's a controller written.

2024-09-04 15:59 UTC, PavelMakarchuk commented on policyengine_api/data/initialise.sql
> +  variable_name VARCHAR(80) NOT NULL
Actually found `mi_retirement_benefits_deduction_tier_three_ss_exempt_not_retired_eligible_people` which is 81. I can't imagine over 100 though

2024-09-04 16:13 UTC, anth-volk commented on policyengine_api/data/initialise.sql
> +  variable_name VARCHAR(80) NOT NULL
My Lord

2024-09-04 20:42 UTC, leehengpan commented on policyengine_api/data/initialise.sql
> +  variable_name VARCHAR(80) NOT NULL
@anth-volk Thank you for reviewing my work. I've made the change accordingly.

2024-09-04 20:44 UTC, leehengpan commented on policyengine_api/data/initialise_local.sql
> +CREATE TABLE IF NOT EXISTS tracers (
@anth-volk Noted. Thank you.

2024-09-06 22:12 UTC, anth-volk requested changes
Thanks for your work on this @leehengpan. I just left a couple comments on the variable flattening utility function, as I believe this implementation may miss a couple of tiers of depth in terms of variables other variables depend upon.

2024-09-06 22:12 UTC, anth-volk commented on policyengine_api/country.py
> +                variables.append(item)
I believe your implementation here will append the entire array, but won't recurse further into `add` items further down the tree. I think you'd want to write a recursive function here that, when there is an adds and/or a subtracts, calls `get_all_variables` on that next tier downward, until eventually you hit some marker of there being no more levels.

2024-09-11 16:11 UTC, anth-volk commented
Closing in light of #1782.

2024-09-11 16:11 UTC, closed without merging