Fix get_search request to return specified number of results, with a max value of 50.
PolicyEngine/policyengine-api pull request #1766
Opened 2024-09-04 08:06 UTC by tawandamoyo

Fixes #422

- Fixed the `get_search` request to return specified number of results instead of just returning 10
- The default is 10, and the maximum value is 50

2024-09-17 21:47 UTC, anth-volk requested changes
Thanks for your work on this @tawandamoyo. Just one change requested.

2024-09-17 21:47 UTC, anth-volk commented on policyengine_api/endpoints/search/search.py
> +            return {
Currently, if a user runs this with an invalid `results` query parameter, the API will return your error message (which is good) but with a status code of 200. Instead, it should really return a failure code - in this case, probably a 400. Could you modify this portion to be similar to the `validate_country` function elsewhere in the API to return the proper status?

2024-09-25 23:59 UTC, anth-volk commented
@tawandamoyo Just wanted to bump this for you

2024-09-26 11:56 UTC, tawandamoyo commented
closed by #1824

2024-09-26 11:56 UTC, closed without merging

2024-09-26 14:28 UTC, anth-volk commented
Wow, good point, don't know how I missed that. Thanks for closing.